import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Foof',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1', they are asigned auto by MongoDb
      name: 'Nike Hawaii Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpeg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Nike Cargo Pant',
      slug: 'nike-cargo-pant',
      category: 'Pants',
      image: '/images/p3.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'Asos Fit Pant',
      slug: 'asos-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Asos',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '5',
      name: 'Zara silk dress',
      slug: 'zara-silk-dress',
      category: 'Dress',
      image: '/images/p5.jpeg',
      price: 265,
      countInStock: 15,
      brand: 'Zara',
      rating: 4.7,
      numReviews: 50,
      description: 'high quality product',
    },
    {
      //_id: '6',
      name: 'Asos cowboy boots',
      slug: 'asos-cowboy-boots',
      category: 'Boots',
      image: '/images/p6.jpeg',
      price: 300,
      countInStock: 45,
      brand: 'Asos',
      rating: 4.9,
      numReviews: 22,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'Siren combat boots',
      slug: 'siren-combat-boots',
      category: 'Boots',
      image: '/images/p7.jpeg',
      price: 400,
      countInStock: 35,
      brand: 'Asos',
      rating: 4.8,
      numReviews: 51,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'Siren handbag',
      slug: 'siren-handbag',
      category: 'handbag',
      image: '/images/p8.jpeg',
      price: 150,
      countInStock: 135,
      brand: 'Asos',
      rating: 4.3,
      numReviews: 21,
      description: 'high quality product',
    },
  ],
};
export default data;
